apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{.Values.backend.name}}
  labels:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
    chart: {{ template "products-shop.chart" . }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
