apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{.Values.frontend.name}}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    release: {{ .Release.Name }}
    chart: {{ template "products-shop.chart" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.name }}
    release: {{ .Release.Name }}
